"""Initial tables: users, profiles, tournaments, matches

Revision ID: d1fb8bfc5380
Revises: c609387228df
Create Date: 2025-11-25 09:02:47.613233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1fb8bfc5380'
down_revision: Union[str, Sequence[str], None] = 'c609387228df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
