"""initial

Revision ID: 777aac33d020
Revises: 
Create Date: 2025-11-26 11:54:34.847494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '777aac33d020'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('telegram', sa.String(length=50), nullable=True),
    sa.Column('instagram', sa.String(length=50), nullable=True),
    sa.Column('youtube', sa.String(length=100), nullable=True),
    sa.Column('discord', sa.String(length=50), nullable=True),
    sa.Column('pes_id', sa.String(length=50), nullable=True),
    sa.Column('team_strength', sa.Integer(), nullable=True),
    sa.Column('favorite_team', sa.String(length=50), nullable=True),
    sa.Column('play_style', sa.String(length=20), nullable=True),
    sa.Column('preferred_formation', sa.String(length=10), nullable=True),
    sa.Column('available_hours', sa.String(length=50), nullable=True),
    sa.Column('coins', sa.Integer(), nullable=False),
    sa.Column('gems', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('total_matches', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('draws', sa.Integer(), nullable=False),
    sa.Column('tournaments_won', sa.Integer(), nullable=False),
    sa.Column('tournaments_played', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_pro', sa.Boolean(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('show_stats', sa.Boolean(), nullable=True),
    sa.Column('last_online', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_profiles_nickname'), 'profiles', ['nickname'], unique=True)
    op.create_table('tournaments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('format', sa.Enum('SINGLE_ELIMINATION', 'DOUBLE_ELIMINATION', 'ROUND_ROBIN', 'SWISS', name='tournamentformat'), nullable=False),
    sa.Column('max_participants', sa.Integer(), nullable=False),
    sa.Column('min_team_strength', sa.Integer(), nullable=False),
    sa.Column('max_team_strength', sa.Integer(), nullable=False),
    sa.Column('entry_fee', sa.Integer(), nullable=False),
    sa.Column('prize_pool', sa.Integer(), nullable=False),
    sa.Column('registration_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registration_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('UPCOMING', 'REGISTRATION', 'LIVE', 'COMPLETED', 'CANCELLED', name='tournamentstatus'), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tournaments_is_featured'), 'tournaments', ['is_featured'], unique=False)
    op.create_index(op.f('ix_tournaments_start_time'), 'tournaments', ['start_time'], unique=False)
    op.create_index(op.f('ix_tournaments_status'), 'tournaments', ['status'], unique=False)
    op.create_index('ix_tournaments_status_start_time', 'tournaments', ['status', 'start_time'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tournament_id', sa.UUID(), nullable=False),
    sa.Column('player1_id', sa.UUID(), nullable=True),
    sa.Column('player2_id', sa.UUID(), nullable=True),
    sa.Column('winner_id', sa.UUID(), nullable=True),
    sa.Column('player1_score', sa.Integer(), nullable=True),
    sa.Column('player2_score', sa.Integer(), nullable=True),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('match_number', sa.Integer(), nullable=False),
    sa.Column('next_match_id', sa.UUID(), nullable=True),
    sa.Column('bracket_position', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'READY', 'PLAYING', 'DISPUTED', 'COMPLETED', name='matchstatus'), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('player1_screenshot', sa.String(length=500), nullable=True),
    sa.Column('player2_screenshot', sa.String(length=500), nullable=True),
    sa.Column('dispute_reason', sa.Text(), nullable=True),
    sa.Column('dispute_resolved_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['dispute_resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['next_match_id'], ['matches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['player1_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['player2_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_match_players', 'matches', ['player1_id', 'player2_id'], unique=False)
    op.create_index('ix_match_tournament_round', 'matches', ['tournament_id', 'round_number'], unique=False)
    op.create_index(op.f('ix_matches_status'), 'matches', ['status'], unique=False)
    op.create_table('tournament_participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tournament_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('is_checked_in', sa.Boolean(), nullable=False),
    sa.Column('is_eliminated', sa.Boolean(), nullable=False),
    sa.Column('final_position', sa.Integer(), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'user_id', name='uq_tournament_user')
    )
    op.create_index('ix_participant_tournament', 'tournament_participants', ['tournament_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_participant_tournament', table_name='tournament_participants')
    op.drop_table('tournament_participants')
    op.drop_index(op.f('ix_matches_status'), table_name='matches')
    op.drop_index('ix_match_tournament_round', table_name='matches')
    op.drop_index('ix_match_players', table_name='matches')
    op.drop_table('matches')
    op.drop_index('ix_tournaments_status_start_time', table_name='tournaments')
    op.drop_index(op.f('ix_tournaments_status'), table_name='tournaments')
    op.drop_index(op.f('ix_tournaments_start_time'), table_name='tournaments')
    op.drop_index(op.f('ix_tournaments_is_featured'), table_name='tournaments')
    op.drop_table('tournaments')
    op.drop_index(op.f('ix_profiles_nickname'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
